services:
  # =========================================================
  # DATABASE
  # =========================================================
  postgres:
    image: postgres:16
    container_name: scanner-postgres
    env_file: [.env]
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro

  adminer:
    image: adminer:4
    depends_on: [postgres]
    ports:
      - "8081:8080"

  # =========================================================
  # CACHES / MESSAGING / SEARCH
  # =========================================================
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: [.env]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  meilisearch:
    image: getmeili/meilisearch:v1.11
    env_file: [.env]
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"

  # =========================================================
  # APPLICATIONS
  # =========================================================
  app_scheduler:
    build: ./app_scheduler
    env_file: [.env]
    depends_on: [postgres]
    command: ["python", "scheduler.py"]
    volumes:
      - ./shared_bcfy:/app/shared_bcfy:ro

  app_ingest:
    build: ./app_ingest
    env_file: [.env]
    depends_on: [redis, minio]
    command: ["python", "collector.py"]
    volumes:
      - ./shared_bcfy:/app/shared_bcfy:ro

  app_transcription:
    build: ./app_transcription
    env_file: [.env]
    depends_on: [postgres, redis, minio]
    command: ["celery", "-A", "worker", "worker", "--loglevel=INFO"]
    volumes:
      - ./shared_bcfy:/app/shared_bcfy:ro

# ===========================================================
# FRONTEND SERVICE
# ===========================================================

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: scanner-frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - app_scheduler
#      - app_ingest
#      - app_transcription
#    environment:
#      - VITE_API_URL=http://localhost:8000
#    restart: unless-stopped



# ===========================================================
# VOLUMES
# ===========================================================
volumes:
  pgdata:
  minio:
